server:
  port: ${FRONTIER_PORT}

spring:
  application:
    name: Icecream e-commerce
    version: 0.1.0
  datasource:
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_FRONTIER_DB}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDENTITY_ISSUER}
          jwk-set-uri: ${IDENTITY_ISSUER}/protocol/openid-connect/certs
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  auth:
    converter:
      resource-id: ${IDENTITY_STOREFRONT_CLIENT_ID}
      principle-attribute: email

springdoc:
  api-docs:
    path: /swagger-resources
  swagger-ui:
    path: /swagger-ui

app:
  cors:
    allowed-origins:
      ${STOREFRONT_URL},

#logging:
#  level:
#    org.springframework.security: TRACE
