server:
  address: ${CHRONOS_HOST}
  port: ${CHRONOS_PORT}

spring:
  application:
    name: chronos
  data:
    mongodb:
      database: ${MONGODB_CHRONOS_DB}
  cloud:
    function:
      definition: helloRabbit;imageDelete # Consumer bean name
    stream:
      bindings:
        imageDelete-in-0:
          binder: rabbit-binder
          destination: consul.image.delete.queue
