server:
  address: ${CHRONOS_HOST}
  port: ${CHRONOS_PORT}

spring:
  application:
    name: chronos
  data:
    mongodb:
      database: ${MONGODB_CHRONOS_DB}
    redis:
      database: 2
  cloud:
    function:
      definition: helloRabbit;deleteImage # Consumer bean name
    stream:
      bindings:
        deleteImage-in-0:
          binder: rabbit-binder
          destination: icecream.consul.media.delete-image

#logging:
#  level:
#    sanlab.icecream:
#      chronos: INFO
#    org.apache.kafka.clients: INFO
#    org.apache.kafka.common.network: INFO
#    org.springframework.cloud.stream.binder.kafka: DEBUG
#    org.springframework.kafka: DEBUG
#    org.springframework.amqp: DEBUG
#    org.springframework.cloud.stream: DEBUG
#    org.springframework.cloud.function: DEBUG

otel:
  instrumentation:
    mongodb.enabled: true
