server:
  address: ${CONSUL_HOST}
  port: ${CONSUL_PORT}
  servlet.context-path: /console

springdoc:
  api-docs:
    path: /swagger-resources
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: consul
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_CONSUL_DB}
    hikari:
      pool-name: ConsulHikariPool
      maximum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  data:
    elasticsearch:
      cluster-nodes: ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      connection-timeout: 5s
      socket-timeout: 10s
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDENTITY_ISSUER}
          jwk-set-uri: ${IDENTITY_ISSUER}/protocol/openid-connect/certs
  cloud:
    stream:
      bindings:
        auditLog-out-0:
          binder: kafka-binder
          destination: icecream.consul.audit-log
        deleteImage-out-0:
          binder: rabbit-binder
          destination: icecream.consul.media.delete-image
  rsocket:
    server:
      port: ${CONSUL_RSOCKET_PORT}

jwt:
  auth:
    converter:
      resource-id: ${IDENTITY_STOREFRONT_CLIENT_ID}
      principle-attribute: email

app:
  cors:
    allowed-origins: >
      ${STOREFRONT_URL},
  temp-dir: ${CONSUL_TEMP_DIR}
  identity:
    url: ${IDENTITY_URL}
    admin:
      username: ${KEYCLOAK_ADMIN}
      password: ${KEYCLOAK_ADMIN_PASSWORD}
    realm: ${IDENTITY_REALM}
    client:
      storefront: ${IDENTITY_STOREFRONT_CLIENT_ID}
      backoffice: ${IDENTITY_BACKOFFICE_CLIENT_ID}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampler:
      probability: 1.0
  otlp:
    metrics:
      export.url: http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT}/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp.endpoint: http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT}/v1/traces
    logging:
      export:
        otlp.endpoint: http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT}/v1/logs

logging:
  level:
    io.opentelemetry: DEBUG
    io.micrometer: DEBUG
