server:
  address: ${CONSUL_HOST}
  port: ${CONSUL_PORT}
  servlet.context-path: /console

springdoc:
  api-docs:
    path: /swagger-resources
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: consul
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_CONSUL_DB}
    hikari:
      pool-name: ConsulHikariPool
      maximum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  data:
    elasticsearch:
      cluster-nodes: ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      connection-timeout: 5s
      socket-timeout: 10s
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDENTITY_ISSUER}
          jwk-set-uri: ${IDENTITY_ISSUER}/protocol/openid-connect/certs
  cloud:
    stream:
      bindings:
        auditLog-out-0:
          binder: kafka-binder
          destination: icecream.consul.audit-log
        deleteImage-out-0:
          binder: rabbit-binder
          destination: icecream.consul.media.delete-image
        notifyPayment-out-0:
          binder: rabbit-binder
          destination: icecream.consul.payment.notify
  rsocket:
    server:
      port: ${CONSUL_RSOCKET_PORT}

app:
  info:
    name: ${spring.application.name}
    description: 'Icecream Consul service'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
  cors:
    allowed-origins: >
      ${STOREFRONT_URL}
  identity:
    url: ${IDENTITY_URL}
    admin:
      username: ${KEYCLOAK_ADMIN}
      password: ${KEYCLOAK_ADMIN_PASSWORD}
    realm: ${IDENTITY_REALM}
    client:
      storefront: ${IDENTITY_STOREFRONT_CLIENT_ID}
      backoffice: ${IDENTITY_BACKOFFICE_CLIENT_ID}
  security:
    api-key: 'user-api-key-456'
    api-keys: >
      ${CONSUL_API_KEY_0},${CONSUL_API_KEY_1}
    jwt:
      converter:
        resource-id: ${IDENTITY_STOREFRONT_CLIENT_ID}
        principle-attribute: email
  payment:
    url: ${PAYMENT_URL}
    webhook:
      secret: ${PAYMENT_WEBHOOK_SECRET}
      host: 'host.docker.internal'
  storefront:
    url: ${STOREFRONT_URL}

otel:
  instrumentation:
    jdbc.enabled: true
    hikaricp.enabled: true
    elasticsearch.enabled: true
    redis.enabled: true
    kafka.enabled: true
    rabbitmq-ampq.enabled: true
