server:
  address: ${CONSUL_HOST}
  port: ${CONSUL_PORT}
  servlet.context-path: /console

springdoc:
  api-docs:
    path: /swagger-resources
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: consul
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_CONSUL_DB}
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDENTITY_ISSUER}
          jwk-set-uri: ${IDENTITY_ISSUER}/protocol/openid-connect/certs
  cloud:
    stream:
      bindings:
        auditlog-out-0:
          binder: rabbit
          destination: audit_log_queue

jwt:
  auth:
    converter:
      resource-id: ${IDENTITY_STOREFRONT_CLIENT_ID}
      principle-attribute: email

app:
  cors:
    allowed-origins: >
      ${STOREFRONT_URL},
  temp-dir: ${CONSUL_TEMP_DIR}
  identity:
    url: ${IDENTITY_URL}
    admin:
      username: ${KEYCLOAK_ADMIN}
      password: ${KEYCLOAK_ADMIN_PASSWORD}
    realm: ${IDENTITY_REALM}
    client:
      storefront: ${IDENTITY_STOREFRONT_CLIENT_ID}
      backoffice: ${IDENTITY_BACKOFFICE_CLIENT_ID}
