server:
  address: ${ECHO_HOST}
  port: ${ECHO_PORT}

spring:
  application:
    name: echo
  rsocket:
    server:
      port: ${ECHO_RSOCKET_PORT}
  data:
    redis:
      database: 3
    mongodb:
      database: ${MONGODB_ECHO_DB}
    cloud:
      function:
        definition: helloRabbit;paymentSuccess
      stream:
        bindings:
          paymentSuccess-in-0:
            binder: rabbit-binder
            destination: icecream.consul.payment.sucess

otel:
  instrumentation:
    mongodb.enabled: true
