server:
  address: ${ECHO_HOST}
  port: ${ECHO_PORT}

spring:
  application:
    name: echo
  rsocket:
    server:
      port: ${ECHO_RSOCKET_PORT}
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_ECHO_DB}
  data:
    redis:
      database: 3
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/master.xml

logging:
  level:
    sanlab.icecream:
      echo: INFO
    org.apache.kafka.clients: INFO
    org.apache.kafka.common.network: INFO
    org.springframework.cloud.stream.binder.kafka: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.cloud.stream: DEBUG
    org.springframework.cloud.function: DEBUG
