server:
  address: ${ECHO_HOST}
  port: ${ECHO_PORT}
  servlet.context-path: /echo

spring:
  application:
    name: echo
  rsocket:
    server:
      port: ${ECHO_RSOCKET_PORT}
  data:
    redis:
      database: 3
    mongodb:
      database: ${MONGODB_ECHO_DB}
      uri: mongodb://admin:password1234@localhost:38001/echo?authSource=admin
  cloud:
    function:
      definition: helloRabbit;notifyPayment;notifyCheckout
    stream:
      bindings:
        notifyPayment-in-0:
          binder: rabbit-binder
          destination: icecream.consul.payment.notify
        notifyCheckout-in-0:
          binder: rabbit-binder
          destination: icecream.consul.checkout.notify
  mail:
    host: ${MAILPIT_HOST}
    port: ${MAILPIT_PORT}
    protocol: smtp

app:
  mail:
    from: caretaker@icecream.com
    from-name: IceCream Care Taker

otel:
  instrumentation:
    mongodb.enabled: true
